### ISSUE TITLE
1. Создать классы данных

### ISSUE THREAD

**Issue by Mewerio** [Mewerio/aston-practice#1]
Необходимо создать классы данных 
    Автобус
                поля: Номер, Модель, Пробег
    Пользователь
                поля: Имя, Пароль, Почта
    Студент
                поля: Номер группы, Средний балл, Номер зачётной книжки
Определить данные классы необходимо, используя шаблон проектирования Builder (внутренним классом). 
Каждый класс должен реализовать интерфейс Comparable и переопределить метод compareTo по всем полям.
Также переопределить в каждом классе метод toString.

**Comment by Lalo841** [comment]
+
